#/bin/bash

kopt="${-}"

set +u
set -e

if [ -z "${DAKINI_HOME}" ]; then
	DAKINI_HOME="$(realpath "$(( [ -n "${BASH_SOURCE}" ] && dirname "$(realpath "${BASH_SOURCE[0]}")" ) || dirname "$(realpath "${0}")")""/../../../../..")"
fi

set -u

CROSS_COMPILE_SYSTEM='netbsd'
CROSS_COMPILE_ARCHITECTURE='x86_64'
CROSS_COMPILE_TRIPLET="${CROSS_COMPILE_ARCHITECTURE}-unknown-${CROSS_COMPILE_SYSTEM}"
CROSS_COMPILE_SYSROOT="${DAKINI_HOME}/${CROSS_COMPILE_TRIPLET}"

CMAKE_TOOLCHAIN_FILE="${DAKINI_HOME}/build/cmake/${CROSS_COMPILE_TRIPLET}.cmake"

CC="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
OBJDUMP="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objdump"
READELF="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export \
	CROSS_COMPILE_TRIPLET \
	CROSS_COMPILE_SYSTEM \
	CROSS_COMPILE_ARCHITECTURE \
	CROSS_COMPILE_SYSROOT \
	CMAKE_TOOLCHAIN_FILE \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	OBJDUMP \
	READELF

set +eu

[[ "${kopt}" = *e*  ]] || set +e
[[ "${kopt}" = *u*  ]] || set +u
